"""initial_models

Revision ID: 545881a53ba8
Revises: None
Create Date: 2026-06-12 19:00:24.155938

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '545881a53ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
